## Drawing Conclusions

In [1]:
import pandas as pd
import numpy as np

jud_data = pd.read_csv('judicial_dataset_predictions.csv')
par_data = pd.read_csv('parachute_dataset.csv')

In [2]:
jud_data.head()

   defendant_id    actual predicted
0         22574  innocent  innocent
1         35637  innocent  innocent
2         39919  innocent  innocent
3         29610    guilty    guilty
4         38273  innocent  innocent

In [3]:
par_data.head()

   parachute_id actual predicted
0          3956  opens     opens
1          2147  opens     opens
2          2024  opens     opens
3          8325  opens     opens
4          6598  opens     opens

In [4]:
jud_actual_innocent = jud_data[jud_data['actual'] == 'innocent']
jud_actual_guilty = jud_data[jud_data['actual'] == 'guilty']
jud_type1Errors = jud_actual_innocent[jud_actual_innocent['predicted'] == 'guilty']
jud_type2Errors = jud_actual_guilty[jud_actual_guilty['predicted'] == 'innocent']

print(f'judgements: {jud_data.shape[0]}')
print(f'errors: {(jud_type1Errors.shape[0] + jud_type2Errors.shape[0]) / jud_data.shape[0]:.2%}')
print(f'type 1 errors: {jud_type1Errors.shape[0]}: {jud_type1Errors.shape[0] / jud_data.shape[0]:.2%}')
print(f'type 2 errors: {jud_type2Errors.shape[0]}: {jud_type2Errors.shape[0] / jud_data.shape[0]:.2%}')

print(f'type 1 errors if all predicted guilty: {jud_actual_innocent.shape[0] / jud_data.shape[0]:.2%}')

judgements: 7283
errors: 4.22%
type 1 errors: 11: 0.15%
type 2 errors: 296: 4.06%
type 1 errors if all predicted guilty: 45.16%

In [5]:
par_actual_opens = par_data[par_data['actual'] == 'opens']
par_actual_fails = par_data[par_data['actual'] == 'fails']
par_type1Errors = par_actual_fails[par_actual_fails['predicted'] == 'opens']
par_type2Errors = par_actual_opens[par_actual_opens['predicted'] == 'fails']

print(f'jumps: {par_data.shape[0]}')
print(f'errors: {(par_type1Errors.shape[0] + par_type2Errors.shape[0]) / par_data.shape[0]:.5f}')
print(f'type 1 errors: {par_type1Errors.shape[0]}: {par_type1Errors.shape[0] / par_data.shape[0]:.5f}')
print(f'type 2 errors: {par_type2Errors.shape[0]}: {par_type2Errors.shape[0] / par_data.shape[0]:5f}')

print(f'type 2 errors if all predicted fail: {par_actual_opens.shape[0] / par_data.shape[0]:5f}')

jumps: 5829
errors: 0.03997
type 1 errors: 1: 0.00017
type 2 errors: 232: 0.039801
type 2 errors if all predicted fail: 0.991765